criado inteface API e implementado no Controller, Service criado e im…
tribos-dev/produdoro-be pull request #13
Opened 2022-01-05 00:04 UTC by Danilo1dev

…plementado, Repository criado e implementado

2022-01-10 22:13 UTC, vinireis requested changes

2022-01-10 22:13 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/usuario/application/api/UsuarioAPI.java
> +	@PutMapping("/{idUsuario}/alteraConfiguracao")
Mudaria a url para somente, "@PutMapping("/{idUsuario}/configuracao".

2022-01-10 22:13 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/usuario/application/service/UsuarioService.java
> +		usuarioPorId.alteraConfiguracaoUsuario(configuracaoUsuario);
mudaria o nome do metodo para atualizaConfiguracoes.

2022-01-10 22:13 UTC, vinireis commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +}]}
é necessário excluir esse arquivo.

2022-01-10 22:13 UTC, vinireis commented on pom.xml
> +</project>
Não entendi

2022-01-16 10:37 UTC, Danilo1dev commented on src/main/java/dev/wakandaacademy/produdoro/usuario/application/api/UsuarioAPI.java
> +	@PutMapping("/{idUsuario}/alteraConfiguracao")
Alterado conforme solicitado

2022-01-16 11:27 UTC, Danilo1dev commented on src/main/resources/META-INF/additional-spring-configuration-metadata.json
> +}]}
excluido

2022-01-16 11:31 UTC, Danilo1dev commented on pom.xml
> +</project>
Vini, não conseguir entender o que quer dizer.

2022-01-18 22:06 UTC, vinireis submitted a review, later dismissed

2022-01-21 20:38 UTC, vinireis approved these changes

2022-01-21 20:39 UTC, merged