Feature/pp 87 usuario define tarefa ativa
tribos-dev/produdoro-be pull request #14
Opened 2022-03-10 20:30 UTC by marcosxavierdev

2022-03-15 23:14 UTC, vinireis requested changes
De maneira geral está top. E funcional.
Coloquei alguns pontos de melhoria. 
Mas o ponto principal é a alteração em lote.

2022-03-15 23:14 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/api/TarefaApi.java
> +	@PatchMapping("v1/tarefa/{idTarefa}")
Acredito que seja melhor:
@PostMapping
"v1/tarefa/{idTarefa}/status"

2022-03-15 23:14 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/service/TarefaSpringMongoDBService.java
>  }
Man, o ideal é joga essa tarefa para o banco.
Fazer uma query. Que pode ser até nativa que atualiza o status de todas as tarefas para inativo.
Desse maneira você evita I/O. E banco é otimizado para esse tipo de tarefa.

2022-03-15 23:14 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/service/TarefaSpringMongoDBService.java
> +
Por que essa quantidade linhas em branco?

2022-03-15 23:14 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/domain/StatusAtivacaoTarefa.java
> +public enum StatusAtivacaoTarefa {
Mudaria o nome para StatusTarefa

2022-03-15 23:14 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/domain/Tarefa.java
> +		public void mudaParaAtivo() {
Mudaria o nome do método para ativa.

2022-03-15 23:14 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/domain/Tarefa.java
> +		public void mudaParaInativo() {
Mudaria o nome do método para inativa.

2022-03-15 23:29 UTC, marcosxavierdev commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/domain/StatusAtivacaoTarefa.java
> +public enum StatusAtivacaoTarefa {
Já existe uma enum StatusTarefa com os valores A_FAZER, CONCLUIDA no Domain, por isso usei o StatusTarefaAtivacao.

2022-03-23 16:48 UTC, vinireis requested changes
Favor implementar as solicitações.
No mais está tudo top.

2022-03-23 16:48 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/service/TarefaSpringMongoDBService.java
> +		desativaTarefas(idUsuario);
Esse método deve ser implementado no Repository.

Ou seja, 

Crie uma assinatura para esse método na inteface application/repository/TarefaRepository

E a implementação concreta, deve ficar na camada de infra em TarefaRepositoryMongoDB

2022-03-23 16:48 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/service/TarefaSpringMongoDBService.java
> +	}
Conforme comentário a assim, mova o método para camada de infra.

2022-03-23 18:08 UTC, vinireis approved these changes
Top demais!

2022-03-23 18:10 UTC, merged