Feature/pp 86 usuario deleta tarefa
tribos-dev/produdoro-be pull request #16
Opened 2022-03-15 19:59 UTC by Rodrigodev1998

2022-03-23 17:01 UTC, vinireis requested changes
Man, cuidado com essa obsessão por linhas em branco.

2022-03-23 17:01 UTC, vinireis commented on src/main/java/dev/wakandaacademy/produdoro/tarefa/application/service/TarefaService.java
> +
Remova os espaços em branco.

2022-03-24 13:30 UTC, vinireis approved these changes

2022-03-25 19:52 UTC, Maabia approved these changes

2022-03-27 22:38 UTC, vinireis approved these changes

2022-03-27 22:40 UTC, merged